site_name: YII2 - La guida italiana
pages:
- Homepage: 'index.md'
- Come Iniziare:    
    - Installazione di Yii: 'getting-started/sub-installing-Yii.md'
    - Iniziamo con un "Ciao": 'getting-started/sub-saying-hello.md'
    - Lavoriamo con i moduli: 'getting-started/sub-working-with-forms.md'
    - Lavoriamo con i database: 'getting-started/sub-working-with-database.md'
    - Generare codice con Gii: 'getting-started/sub-generate-code-gii.md'
    - Guardiamo avanti: 'getting-started/sub-looking-ahead.md'
- Struttura dell'Applicazione:
    - Panoramica: 'application-structure/sub-overview.md'
    - Entry Script: 'application-structure/sub-entry-script.md'
    - Applicazioni: 'application-structure/sub-applications.md' 
    - Componenti applicativi: 'application-structure/sub-application-components.md'
    - Controllori: 'application-structure/sub-controllers.md'
    - Modelli: 'application-structure/sub-models.md'
    - Viste: 'application-structure/sub-views.md'
    - Moduli: 'application-structure/sub-modules.md'
    - Filtri: 'application-structure/sub-filters.md'
    - Widget: 'application-structure/sub-widget.md'
    - Assets: 'application-structure/sub-assets.md'
    - Estensioni: 'application-structure/sub-extensions.md'
- Gestione delle richieste:
    - Panoramica sulla gestione delle richieste: 'handling-requests/sub-request-overview.md'
    - Bootstrapping: 'handling-requests/sub-bootstrapping.md'
    - Routing e creazione degli URL: 'handling-requests/sub-routing-url-creation.md'
    - Requests: 'handling-requests/sub-requests.md'
    - Responses: 'handling-requests/sub-responses.md'
    - Session & Cookies: 'handling-requests/sub-session-cookies.md'
    - Gestione degli errori: 'handling-requests/sub-handling-error.md'
    - Registrazione: 'handling-requests/sub-logging.md'
- Concetti chiave:
    - Componenti: 'key-concepts/sub-components.md'
    - Proprietà: 'key-concepts/sub-properties.md'
    - Eventi: 'key-concepts/sub-events.md'
    - Comportamenti (Behaviors): 'key-concepts/sub-behaviors.md'
    - Configurazioni: 'key-concepts/sub-configurations.md'
    - Alias: 'key-concepts/sub-alias.md'
    - Classe "Autoloading": 'key-concepts/sub-autoloading-class.md'
    - Localizzatore di servizi: 'key-concepts/sub-service-locator.md'
    - Contenitore Dependency Injection: 'key-concepts/sub-dependency-injection-container.md'
- Lavorare con i Database:
    - Accesso ai dati tramite oggetti: 'working-with-databases/sub-data-access-object.md'
    - Generatore di Query: 'working-with-databases/sub-query-builder.md'
    - Active Record: 'working-with-databases/sub-active-record.md'
    - Migrazoni: 'working-with-databases/sub-migrations.md'
theme: 'material'
extra:
      primary: 'teal'

markdown_extensions:
    - admonition
    - def_list
    - toc:
        permalink: true
    - footnotes
    - meta

extra:
  feature:
    tabs: true
  palette:
    primary: 'teal'
    accent: 'deep orange'

site_author: Lorenzo Milicia
copyright: © MIT - Lorenzo Milicia - 2017
repo_url: https://github.com/Milicia4/Yii2-Ita.git
google_analytics: ['UA-109845735-1', 'auto']
site_description: Guida italiana del framework PHP Yii 2.0
repo_name: GitHub
